INSERT INTO Equipment VALUES
('Abacus'),
('Acid (vial)'),
('Alchemists fire (flask)'),
('Alchemists supplies'),
('Amulet'),
('Animal Feed (1 day)'),
('Antitoxin (vial)'),
('Arrow'),
('Backpack'),
('Bagpipes'),
('Ball bearings (bag of 1,000)'),
('Barding: Breastplate'),
('Barding: Chain mail'),
('Barding: Chain shirt'),
('Barding: Half plate'),
('Barding: Hide'),
('Barding: Leather'),
('Barding: Padded'),
('Barding: Plate'),
('Barding: Ring mail'),
('Barding: Scale mail'),
('Barding: Splint'),
('Barding: Studded Leather'),
('Barrel'),
('Basket'),
('Battleaxe'),
('Bedroll'),
('Bell'),
('Bit and bridle'),
('Blanket'),
('Block and tackle'),
('Blowgun'),
('Blowgun needle'),
('Book'),
('Bottle, glass'),
('Breastplate'),
('Brewers supplies'),
('Bucket'),
('Burglars Pack'),
('Calligraphers supplies'),
('Caltrops'),
('Camel'),
('Candle'),
('Carpenters tools'),
('Carriage'),
('Cart'),
('Cartographers tools'),
('Case, crossbow bolt'),
('Case, map or scroll'),
('Chain (10 feet)'),
('Chain Mail'),
('Chain Shirt'),
('Chalk (1 piece)'),
('Chariot'),
('Chest'),
('Climbers Kit'),
('Clothes, common'),
('Clothes, costume'),
('Clothes, fine'),
('Clothes, travelers'),
('Club'),
('Cobblers tools'),
('Component pouch'),
('Cooks utensils'),
('Crossbow bolt'),
('Crossbow, hand'),
('Crossbow, heavy'),
('Crossbow, light'),
('Crowbar'),
('Crystal'),
('Dagger'),
('Dart'),
('Dice set'),
('Diplomats Pack'),
('Disguise Kit'),
('Donkey'),
('Drum'),
('Dulcimer'),
('Dungeoneers Pack'),
('Elephant'),
('Emblem'),
('Entertainers Pack'),
('Explorers Pack'),
('Fishing tackle'),
('Flail'),
('Flask or tankard'),
('Flute'),
('Forgery Kit'),
('Galley'),
('Glaive'),
('Glassblowers tools'),
('Grappling hook'),
('Greataxe'),
('Greatclub'),
('Greatsword'),
('Halberd'),
('Half Plate'),
('Hammer'),
('Hammer, sledge'),
('Handaxe'),
('Healers Kit'),
('Herbalism Kit'),
('Hide'),
('Holy water (flask)'),
('Horn'),
('Horse, draft'),
('Horse, riding'),
('Hourglass'),
('Hunting trap'),
('Ink (1 ounce bottle)'),
('Ink pen'),
('Javelin'),
('Jewelers tools'),
('Jug or pitcher'),
('Keelboat'),
('Ladder (10-foot)'),
('Lamp'),
('Lance'),
('Lantern, bullseye'),
('Lantern, hooded'),
('Leather'),
('Leatherworkers tools'),
('Light hammer'),
('Lock'),
('Longbow'),
('Longship'),
('Longsword'),
('Lute'),
('Lyre'),
('Mace'),
('Magnifying glass'),
('Manacles'),
('Masons tools'),
('Mastiff'),
('Maul'),
('Mess Kit'),
('Mirror, steel'),
('Morningstar'),
('Mule'),
('Navigators tools'),
('Net'),
('Oil (flask)'),
('Orb'),
('Padded'),
('Painters supplies'),
('Pan flute'),
('Paper (one sheet)'),
('Parchment (one sheet)'),
('Perfume (vial)'),
('Pick, miners'),
('Pike'),
('Piton'),
('Plate'),
('Playing card set'),
('Poison, basic (vial)'),
('Poisoners Kit'),
('Pole (10-foot)'),
('Pony'),
('Pot, iron'),
('Potion of healing'),
('Potters tools'),
('Pouch'),
('Priests Pack'),
('Quarterstaff'),
('Quiver'),
('Ram, portable'),
('Rapier'),
('Rations (1 day)'),
('Reliquary'),
('Riding'),
('Ring Mail'),
('Robes'),
('Rod'),
('Rope, hempen (50 feet)'),
('Rope, silk (50 feet)'),
('Rowboat'),
('Sack'),
('Saddle, Exotic'),
('Saddle, Military'),
('Saddle, Pack'),
('Saddlebags'),
('Sailing ship'),
('Scale Mail'),
('Scale, merchants'),
('Scholars Pack'),
('Scimitar'),
('Sealing wax'),
('Shawm'),
('Shield'),
('Shortbow'),
('Shortsword'),
('Shovel'),
('Sickle'),
('Signal whistle'),
('Signet ring'),
('Sled'),
('Sling'),
('Sling bullet'),
('Smiths tools'),
('Soap'),
('Spear'),
('Spellbook'),
('Spike, iron'),
('Splint'),
('Sprig of mistletoe'),
('Spyglass'),
('Stabling (1 day)'),
('Staff'),
('Studded Leather'),
('Tent, two-person'),
('Thieves tools'),
('Tinderbox'),
('Tinkers tools'),
('Torch'),
('Totem'),
('Trident'),
('Vial'),
('Viol'),
('Wagon'),
('Wand'),
('War pick'),
('Warhammer'),
('Warhorse'),
('Warship'),
('Waterskin'),
('Weavers tools'),
('Whetstone'),
('Whip'),
('Woodcarvers tools'),
('Wooden staff'),
('Yew wand')