create table [dbo].[Saves](
	[ID]		 INT IDENTITY(1,1)	NOT NULL,
	[Name]		 Nvarchar(40)		NOT NULL,
	[OwnerID]	 Nvarchar(128)		,
	[Monster1]   Nvarchar(128)		,
	[Monster2]   Nvarchar(128)		,
	[Monster3]   Nvarchar(128)		,
	[Monster4]   Nvarchar(128)		,
	[Monster5]   Nvarchar(128)		,
	[Monster6]   Nvarchar(128)		,
	[Monster7]   Nvarchar(128)		,
	[Monster8]   Nvarchar(128)		,
	[Monster9]	 Nvarchar(128)		,
	[Monster10]  Nvarchar(128)		,
	[Monster11]  Nvarchar(128)		,
	[Monster12]  Nvarchar(128)		,
	[Monster13]  Nvarchar(128)		,
	[Monster14]  Nvarchar(128)		,
	[Monster15]  Nvarchar(128)		,
	[Monster16]  Nvarchar(128)		,
	[Monster17]  Nvarchar(128)		,
	[Monster18]  Nvarchar(128)		,
	[Monster19]  Nvarchar(128)		,
	[Monster20]  Nvarchar(128)		,
	[Magic]      Nvarchar(500)

	CONSTRAINT [PK_dbo.Saves] PRIMARY KEY CLUSTERED ([ID] ASC),
	
);

create table [dbo].[Players](
	[ID]		INT IDENTITY(1,1)	NOT NULL,
	[OwnerID]	Nvarchar(128)		,
	[GameID]	Int					,
	[Name]		NvarChar(30)		Not NULL,
	[Size]		NvarChar(15)		,
	[Type]		NvarChar(20)		,
	[Aligment]	NvarChar(20)		,
	[ArmorClass] Int				,
	[HitPoints] Int					,
	[Strength]	int					,
	[Dexterity] int					,
	[Constitution] int				,
	[Intelligence] int				,
	[Wisdom]	int					,
	[Charisma] int					,
	[Languages] NvarChar(500)		,
	[Speed] NvarChar(500)			,
	[Proficiencies] NvarChar(500)	,
	[DamageResistance] NvarChar(500),
	[ConditionImmunity] NvarChar(500),
	[Senses] NvarChar(500)			,
	[SpecialAbility] NvarChar(500)	,
	[Actions] NVarChar(MAX)

	CONSTRAINT [PK_dbo.Players] PRIMARY KEY CLUSTERED ([ID] ASC),
);