create table [dbo].[Creatures](
	[ID] INT IDENTITY (1,1) NOT NULL,
	[Name] NvarChar(30) Not NULL,
	[Size] NvarChar(15) Not NULL,
	[Type] NvarChar(20) Not Null,
	[SubType] NvarChar(20),
	[Aligment] NvarChar(20) Not Null,
	[ArmorClass] Int Not Null,
	[HitPoints] Int Not Null,
	[HitDice] NvarChar(10) Not Null,
	[Strength] int Not Null,
	[Dexterity] int Not Null,
	[Constitution] int Not Null,
	[Intelligence] int Not Null,
	[Wisdom] int Not Null,
	[Charisma] int Not Null,
	[Languages] NvarChar(500),
	[ChallangeRating] Float Not Null,
	[Speed] NvarChar(500) Not Null,
	[Proficiencies] NvarChar(500),
	[DamageResistance] NvarChar(500),
	[DamageVulnerability] NvarChar(500),
	[DamageImmunity] NvarChar(500),
	[ConditionImmunity] NvarChar(500),
	[Senses] NvarChar(500) Not Null,
	[SpecialAbility] NvarChar(500),
	[Actions] NVarChar(MAX),
	[LegendaryActions] NVarChar(MAX)

	CONSTRAINT [PK_dbo.Creatures] PRIMARY KEY CLUSTERED ([ID] ASC)
);