create table [dbo].[Creatures](
	[ID] INT IDENTITY (1,1) NOT NULL,
	[Name] NvarChar(30) Not NULL,
	[Size] NvarChar(15) Not NULL,
	[Type] NvarChar(20) Not Null,
	[SubType] NvarChar(20),
	[Aligment] NvarChar(20) Not Null,
	[ArmorClass] Int Not Null,
	[HitPoints] Int Not Null,
	[HitDice] NvarChar(10) Not Null,
	[Strength] int Not Null,
	[Dexterity] int Not Null,
	[Constitution] int Not Null,
	[Intelligence] int Not Null,
	[Wisdom] int Not Null,
	[Charisma] int Not Null,
	[Speed] JSON Not Null,
	[Proficiencies] JSON Not Null,
	[DamageResistance] JSON Not Null,
	[DamageVulnerability] JSON Not Null,
	[DamageImmunitiy] JSON Not Null,
	[Senses] JSON Not Null,
	[Languages] JSON Not Null,
	[ChallangeRating] JSON Not Null,
	[SpecialAbility] JSON Not Null
);